### ISSUE TITLE
Request your work to be included in the awesome Zepp OS project

### ISSUE THREAD

**Issue by MyoungXUE** [LeKovr/hocon-zepp#1]
Hello @LeKovr 

Please allow me to introduce myself, I am Myoung XUE, an engineer from Zepp OS Team.

We have an awesome project https://github.com/zepp-health/awesome-zeppos, as the name suggests, where we include many projects from the community that are relevant to Zepp OS.

We noticed that several of your projects are publicly available on Github and would like to ask your permission to include them in the official awesome zeppos repository.

Hopefully, we can get your approval and your project will help more developers in the community.

**Comment by LeKovr** [comment]
Hi, @MyoungXUE.
First of all I would like to thank your team for  Zepp OS itself. Nice OS and it has taken small of time to develop an application for it.
Of  course, I will be glad to see my projects included in awesome list. You have my permission now;-)
